### ISSUE TITLE
Where is the Fizz

### ISSUE THREAD

**Issue by alexapostolu** [PacificDolphin/FizzBuzz#1]

**Comment by PacificDolphin** [comment]
fizz is a very interesting, very clever, innovative feature. we are currently working on it. we are unable to provide an expected finish date. thank you for your patience and interest in this project.

**Comment by PacificDolphin** [comment]
after working tirelessly, we are proud to announce the release of fizz. not only that, in return for your eager dedication and support for this product, we are ecstatic to say buzz is also uploaded! again, we thank you for your commitment and hope you enjoy our releases.
