### ISSUE TITLE
Where is the buzz

### ISSUE THREAD

**Issue by alexapostolu** [PacificDolphin/FizzBuzz#2]

**Comment by PacificDolphin** [comment]
buzz is a very interesting, very clever, innovative feature. we are currently working on it. we are unable to provide an expected finish date. thank you for your patience and interest in this project.

**Comment by PacificDolphin** [comment]
after working tirelessly, we are proud to announce the release of buzz. not only that, in return for your eager dedication and support for this product, we are ecstatic to say fizz is also uploaded!
